//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPartsTCE.SROuvidoria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SROuvidoria.OuvidoriaSoap")]
    public interface OuvidoriaSoap {
        
        // CODEGEN: Generating message contract since element name nome from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarEmail", ReplyAction="*")]
        WebPartsTCE.SROuvidoria.EnviarEmailResponse EnviarEmail(WebPartsTCE.SROuvidoria.EnviarEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPartsTCE.SROuvidoria.EnviarEmailResponse> EnviarEmailAsync(WebPartsTCE.SROuvidoria.EnviarEmailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarEmail", Namespace="http://tempuri.org/", Order=0)]
        public WebPartsTCE.SROuvidoria.EnviarEmailRequestBody Body;
        
        public EnviarEmailRequest() {
        }
        
        public EnviarEmailRequest(WebPartsTCE.SROuvidoria.EnviarEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cpf;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string assunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string mensagem;
        
        public EnviarEmailRequestBody() {
        }
        
        public EnviarEmailRequestBody(string nome, string email, string fone, string cpf, string assunto, string mensagem) {
            this.nome = nome;
            this.email = email;
            this.fone = fone;
            this.cpf = cpf;
            this.assunto = assunto;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPartsTCE.SROuvidoria.EnviarEmailResponseBody Body;
        
        public EnviarEmailResponse() {
        }
        
        public EnviarEmailResponse(WebPartsTCE.SROuvidoria.EnviarEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviarEmailResult;
        
        public EnviarEmailResponseBody() {
        }
        
        public EnviarEmailResponseBody(string EnviarEmailResult) {
            this.EnviarEmailResult = EnviarEmailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OuvidoriaSoapChannel : WebPartsTCE.SROuvidoria.OuvidoriaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OuvidoriaSoapClient : System.ServiceModel.ClientBase<WebPartsTCE.SROuvidoria.OuvidoriaSoap>, WebPartsTCE.SROuvidoria.OuvidoriaSoap {
        
        public OuvidoriaSoapClient() {
        }
        
        public OuvidoriaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OuvidoriaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OuvidoriaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OuvidoriaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPartsTCE.SROuvidoria.EnviarEmailResponse WebPartsTCE.SROuvidoria.OuvidoriaSoap.EnviarEmail(WebPartsTCE.SROuvidoria.EnviarEmailRequest request) {
            return base.Channel.EnviarEmail(request);
        }
        
        public string EnviarEmail(string nome, string email, string fone, string cpf, string assunto, string mensagem) {
            WebPartsTCE.SROuvidoria.EnviarEmailRequest inValue = new WebPartsTCE.SROuvidoria.EnviarEmailRequest();
            inValue.Body = new WebPartsTCE.SROuvidoria.EnviarEmailRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.email = email;
            inValue.Body.fone = fone;
            inValue.Body.cpf = cpf;
            inValue.Body.assunto = assunto;
            inValue.Body.mensagem = mensagem;
            WebPartsTCE.SROuvidoria.EnviarEmailResponse retVal = ((WebPartsTCE.SROuvidoria.OuvidoriaSoap)(this)).EnviarEmail(inValue);
            return retVal.Body.EnviarEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPartsTCE.SROuvidoria.EnviarEmailResponse> WebPartsTCE.SROuvidoria.OuvidoriaSoap.EnviarEmailAsync(WebPartsTCE.SROuvidoria.EnviarEmailRequest request) {
            return base.Channel.EnviarEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPartsTCE.SROuvidoria.EnviarEmailResponse> EnviarEmailAsync(string nome, string email, string fone, string cpf, string assunto, string mensagem) {
            WebPartsTCE.SROuvidoria.EnviarEmailRequest inValue = new WebPartsTCE.SROuvidoria.EnviarEmailRequest();
            inValue.Body = new WebPartsTCE.SROuvidoria.EnviarEmailRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.email = email;
            inValue.Body.fone = fone;
            inValue.Body.cpf = cpf;
            inValue.Body.assunto = assunto;
            inValue.Body.mensagem = mensagem;
            return ((WebPartsTCE.SROuvidoria.OuvidoriaSoap)(this)).EnviarEmailAsync(inValue);
        }
    }
}
